CUS1166_Project_Template-master/app/models.py
#from flask import url_for
from app import db
from datetime import datetime
#from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Task(db.Model):

    task_id = db.Column(db.Integer, primary_key=True)
    task_desc = db.Column(db.String(128), index=True)
    task_status = db.Column(db.String(128))

class Appointment(db.Model):
    __tablename__ = "Appointment"
    appt_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    appt_title = db.Column(db.String, nullable=False)
    appt_datetime = db.Column(db.DateTime, nullable=False)
    location = db.Column(db.String, nullable=False)
    add_notes = db.Column(db.String, nullable=False)
    status = db.Column(db.String, nullable=False)
    customer_Name = db.Column(db.String, nullable=False)
    customer_email = db.Column(db.String, nullable=False)

CUS1166_Project_Template-master/app/main/forms.py
# import flask_wtf
import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.fields.html5 import DateField, TimeField
from wtforms.validators import ValidationError, DataRequired, Length, Email

class TaskForm(FlaskForm):
    task_desc = StringField('task_desc', validators=[DataRequired()])
    task_status_completed = SelectField('Status', choices=[('todo','Todo'),('doing','Doing'),('done','Done')])
    submit = SubmitField('submit')

class AppointmentF(FlaskForm):
    title = SelectField('Appointment Type', choices=[('Fixing AC Unit', 'Fixing AC Unit'),('Billing', 'Billing'),('Other','Other')])
    date = StringField('Date', validators=[DataRequired()], default=datetime.datetime.now().date())
    time = StringField('Time', validators=[DataRequired()], default=datetime.datetime.now().time())
    location = StringField('Location', validators=[DataRequired()])
    name = StringField('Customer Name', validators=[DataRequired(), Length(3, max=45, message='None')])
    email = StringField('Email', validators=[DataRequired(), Email()])
    notes = StringField('Any other notes?')
    submit = SubmitField('submit')

    def validate_email(self, email):
        super()
        appointment = Appointment.query.filter_by(customer_email=email.data).first()
        if appointment is not None:
            raise ValidationError('This email has been taken')

CUS1166_Project_Template-master/app.py
import sys

from app import create_app, db

app = create_app()

CUS1166_Project_Template-master/app/__init__.py
from flask import Flask, current_app

from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask import Blueprint

## from flask_migrate  import Migrate
## from flask_login import LoginManager

# Instanciate modules used in the project.

## migrate = Migrate()
## login = LoginManager()
db = SQLAlchemy()

#bp = Blueprint('main',__name__, template_folder='../main/templates')

def create_app(config_class=Config):

    app = Flask(__name__)

    # load configuration parameters from Config class
    app.config.from_object(config_class)

    # Initialize app for db and migrate modules.
    db.init_app(app)
    bootstrap = Bootstrap(app)
    ##migrate.init_app(app,db)
    ##login.init_app(app)


    # Added the autho blueprint
    ##from app.auth import bp as auth_routes_bp
    ##app.register_blueprint(auth_routes_bp,url_prefix='/auth')


    # Added the main app.
    from app.main import bp as main_routes_bp
    app.register_blueprint(main_routes_bp)
    return app;

CUS1166_Project_Template-master/app/main/__init__.py
# Imports the Blueprint class from flask.
from flask import Blueprint

bp = Blueprint('main',__name__, template_folder='../main/templates')

from app.main import routes

CUS1166_Project_Template-master/app/main/routes.py
import datetime
from flask import render_template, redirect, url_for, request, flash
from app.main import *
from app.main import bp
from sqlalchemy.testing import db
from app.models import *
from app.models import Task
from app.models import Appointment
from .forms import TaskForm, AppointmentF

# Main route of the applicaitons.
@bp.route('/', methods=['GET','POST'])
def index():
    return render_template("main/index.html")

@bp.route('/appointment', methods=['GET', 'POST'])
def appointment():
    return render_template("main/appointment.html")

@bp.route('/createappt', methods=['GET', 'POST'])
def appt():
    form = Appointment()

    if form.validate_on_submit():
        appts = AppointmentF()
        appts.appt_title=form.title.data
        appts.appt_datetime=datetime.datetime.combine(form.date.data, form.time.data)
        appts.location=form.location.data
        appts.add_notes=form.notes.data
        appts.customer_Name=form.name.data
        appts.customer_email=form.email.data
        appts.appointment.status = "Created Appointment"
        db.session.add(appts)
        db.session.commit()
        flash('Successfully created the appointment!', category='success')
        return redirect(url_for('main/viewappt'), appts=appts)
    return render_template("main/createappt.html", appts=appts, form=form)

@bp.route('/editappt/<int:appt_id>', methods=['GET', 'POST'])
def edit(appt_id):
    form = AppointmentF()
    appt = Appointment.query.get(appt_id)
    if(request.method == "POST"):
        appt.appt_title = form.title.data
        appt.appt_datetime = datetime.datetime.combine(form.date.data, form.time.data)
        appt.location = form.location.data
        appt.add_notes = form.notes.data
        appt.customer_Name = form.name.data
        appt.customer_email = form.email.data
        appt.status = "Edited Appointment"
        db.session.add(appt)
        db.session.commit()
        return redirect(url_for('viewappt.html', appt=appt))
    return render_template("main/editappt.html", form=form, appt=appt)

@bp.route('/deleteappt/<int:appt_id>', methods=['GET', 'POST', 'DELETE'])
def delete(appt_id):
    appt = Appointment.query.get(appt_id)
    appt.status = "Deleted"
    db.session.delete(appt)
    db.session.commit()
    flash('Successfully deleted appointment!', category='success')
    return render_template("main/viewappt.html")

@bp.route('/apptview', methods=['GET', 'POST'])
def apptview():
    appts = Appointment.query.all()
    return render_template("main/viewappt.html", appts=appts)

#
#  Route for viewing and adding new tasks.
@bp.route('/todolist', methods=['GET','POST'])
def todolist():
    form = TaskForm()

    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.
        new_task = Task()
        new_task.task_desc =  form.task_desc.data
        new_task.task_status = form.task_status_completed.data

        db.session.add(new_task)
        db.session.commit()

        # Redirect to this handler - but without form submitted - gets a clear form.
        return redirect(url_for('main.todolist'))

    todo_list = db.session.query(Task).all()

    return render_template("main/todolist.html",todo_list = todo_list,form= form)


#
# Route for removing a task
@bp.route('/todolist/remove/<int:task_id>', methods=['GET','POST'])
def remove_task(task_id):

    # Query database, remove items
    Task.query.filter(Task.task_id == task_id).delete()
    db.session.commit()

    return redirect(url_for('main.todolist'))


#
# Route for editing a task

@bp.route('/todolist/edit/<int:task_id>', methods=['GET','POST'])
def edit_task(task_id):
    form = TaskForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.

        current_task = Task.query.filter_by(task_id=task_id).first_or_404()
        current_task.task_desc =  form.task_desc.data
        current_task.task_status = form.task_status_completed.data

        db.session.add(current_task)
        db.session.commit()
        # After editing, redirect to the view page.
        return redirect(url_for('main.todolist'))

    # get task for the database.
    current_task = Task.query.filter_by(task_id=task_id).first_or_404()

    # update the form model in order to populate the html form.
    form.task_desc.data =     current_task.task_desc
    form.task_status_completed.data = current_task.task_status

    return render_template("main/todolist_edit_view.html",form=form, task_id = task_id)

CUS1166_Project_Template-master/app/templates/createappt.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
<h1>Create a new appointment.</h1>
    <form method="POST" action="{{url_for('main.createappt')}}" >
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.title.label}}
            {% if form.title.errors %}
                {% for e in form.Username.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.Username(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.date.label}}
            {% if form.date.errors %}
                {% for e in form.date.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.date(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.time.label}}
            {% if form.time.errors %}
                {% for e in form.time.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.time(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.location.label}}
            {% if form.location.errors %}
                {% for e in form.location.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.location(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.name.label}}
            {% if form.name.errors %}
                {% for e in form.name.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.name(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.email.label}}
            {% if form.email.errors %}
                {% for e in form.email.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.email(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.notes.label}}
            {% if form.notes.errors %}
                {% for e in form.notes.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.notes(class_='form-control') }}
        </div>

        <div class="form-group">
            {{ form.submit(class_='btn btn-primary') }}
        </div>
    </form>
</div>
{% endblock content %}

CUS1166_Project_Template-master/app/templates/editappt.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
<h1>Edit an Appointment.</h1>
    <form method="POST" action="{{url_for('main.editappt')}}" >
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.title.label}}
            {% if form.title.errors %}
                {% for e in form.Username.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.Username(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.date.label}}
            {% if form.date.errors %}
                {% for e in form.date.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.date(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.time.label}}
            {% if form.time.errors %}
                {% for e in form.time.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.time(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.location.label}}
            {% if form.location.errors %}
                {% for e in form.location.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.location(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.name.label}}
            {% if form.name.errors %}
                {% for e in form.name.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.name(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.email.label}}
            {% if form.email.errors %}
                {% for e in form.email.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.email(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.notes.label}}
            {% if form.notes.errors %}
                {% for e in form.notes.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.notes(class_='form-control') }}
        </div>

        <div class="form-group">
            {{ form.submit(class_='btn btn-primary') }}
        </div>
    </form>
</div>
{% endblock content %}

CUS1166_Project_Template-master/app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block metas %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Individual Project Template for CUS 1166">
  <meta name="author" content="Christoforos Christoforou">
{% endblock  %}

{% block title %}
  CUS 1166 - Individual or Group Project Template
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/cus1166_custom.css')}}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
{% endblock %}


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">CUS1166 Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {%  block menuitems %}

      {%  endblock menuitems%}
    </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
    {% block main_content %}
    {% endblock main_content %}
      {% block footer %}
      <!-- Footer -->
      <footer class="page-footer font-small blue fixed-bottom">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
          <a href="https://www.researchgate.net/profile/Christoforos_Christoforou"> Template project for CUS1166 by Dr. Christoforos Christoforou</a>
        </div>
        <!-- Copyright -->

      </footer>
      <!-- Footer -->
      {% endblock footer %}
{% endblock content%}

CUS1166_Project_Template-master/app/templates/main/appointment.html
{% extends "menu.html" %}

{% block content %}
<h1>Appointment Actions:</h1>
    <p><a href="{{url_for('main.createappt')}}">Create a New Appointment</a></p>
    <p><a href="{{url_for('main.editappt')}}">Edit an Existing Appointment</a></p>
    <p><a href="{{url_for('main.viewappt')}}">View Appointments</a></p>
    <p><a href="{{url_for('main.viewappt')}}">Delete an Existing Appointment</a></p>

{% endblock content %}

CUS1166_Project_Template-master/app/templates/main/createappt.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
<h1>Create a new appointment.</h1>
    <form method="POST" action="" >
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.title.label}}
            {% if form.title.errors %}
                {% for e in form.Username.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.Username(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.date.label}}
            {% if form.date.errors %}
                {% for e in form.date.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.date(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.time.label}}
            {% if form.time.errors %}
                {% for e in form.time.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.time(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.location.label}}
            {% if form.location.errors %}
                {% for e in form.location.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.location(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.name.label}}
            {% if form.name.errors %}
                {% for e in form.name.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.name(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.email.label}}
            {% if form.email.errors %}
                {% for e in form.email.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.email(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.notes.label}}
            {% if form.notes.errors %}
                {% for e in form.notes.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.notes(class_='form-control') }}
        </div>

        <div class="form-group">
            {{ form.submit(class_='btn btn-primary') }}
        </div>
    </form>
</div>
{% endblock content %}

CUS1166_Project_Template-master/app/templates/main/editappt.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
<h1>Edit an Appointment.</h1>
    <form method="POST" action="" >
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.title.label}}
            {% if form.title.errors %}
                {% for e in form.Username.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.Username(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.date.label}}
            {% if form.date.errors %}
                {% for e in form.date.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.date(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.time.label}}
            {% if form.time.errors %}
                {% for e in form.time.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.time(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.location.label}}
            {% if form.location.errors %}
                {% for e in form.location.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.location(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.name.label}}
            {% if form.name.errors %}
                {% for e in form.name.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.name(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.email.label}}
            {% if form.email.errors %}
                {% for e in form.email.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.email(class_='form-control') }}
        </div>

        <div class="form-group">
            {{form.notes.label}}
            {% if form.notes.errors %}
                {% for e in form.notes.errors %}
                    <p class="help-block text-danger">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.notes(class_='form-control') }}
        </div>

        <div class="form-group">
            {{ form.submit(class_='btn btn-primary') }}
        </div>
    </form>
</div>
{% endblock content %}

CUS1166_Project_Template-master/app/templates/main/index.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5">Individual Project for CUS1166 -</h1>
      <p class="lead">Get ready to showcase your Software Engineering Skills!</p>
      <ul class="list-unstyled">
        <li> Applying agile methodoloies in software development </li>
        <li>Realizing a full sprint implementing use-case  </li>
        <li> Using Flask, ORMs, Forms to implement new features </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/todolist.html
{% extends "menu.html" %}

{% block main_content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>
                        <form method="POST" action="{{url_for('main.todolist')}}" >

                        <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>

                       <!-- Show current tasks if avaiblae -->
                        <div class="list-wrapper">
                            <ul class="d-flex flex-column-reverse todo-list">
                             {% for task in todo_list %}

                                {% if 'done' == task.task_status%}
                                    <li class="completed">
                                {% else %}
                                    <li>
                                {% endif %}
                                    <a href="{{url_for('main.edit_task',task_id=task.task_id)}}">
                                         <i class="fas fa-edit"></i>
                                    </a>

                                    <div class="form-check">

                                      <label class="form-check-label">
                                          {% if 'done' == task.task_status %}
                                            {{task.task_desc}} - <span class="badge badge-success">{{task.task_status}}</span>
                                          {% elif 'doing' == task.task_status %}
                                            {{task.task_desc}} - <span class="badge badge-warning">{{task.task_status}}</span>
                                          {% elif 'todo' == task.task_status %}
                                             {{task.task_desc}} - <span class="badge badge-danger">{{task.task_status}}</span>
                                          {% endif %}
                                            <i class="input-helper"></i>
                                      </label>
                                    </div>
                                    <a href="{{url_for('main.remove_task',task_id=task.task_id)}}" class="remove"><i class="fas fa-times"></i></a>
                              </li>
                             {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/todolist_edit_view.html
{% extends "menu.html" %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>
                        <form method="POST" action="{{url_for('main.edit_task',task_id=task_id)}}" >
                            <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/viewappt.html
{% extends "menu.html" %}

{% block content %}
    {% for appts in Appointment %}
        <ul>
            <li>Title: {{appts.appt_title}}</li>
            <li>Appointment Date: {{appts.appt_date}}</li>
            <li>Appointment Time: {{appts.start_time}}</li>
            <li>Location: {{appts.location}}</li>
            <li>Notes: {{appts.add_notes}}</li>
            <li>Customer Name: {{appts.customer_Name}}</li>
            <li>Customer Email: {{appts.customer_email}}</li>
            <li>Status: {{appts.status}}</li>
        </ul>
    {% endfor %}
{% endblock content %}

CUS1166_Project_Template-master/app/templates/menu.html
{% extends "layout.html" %}
{%  block menuitems %}
<li class="nav-item active">
  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.todolist')}}">Sample Use Case</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.appointment')}}">Appointment</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.createappt')}}">Create An Appointment</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.editappt')}}">Edit An Appointment</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.viewappt')}}">View All Appointment(s)</a>
</li>
{%  endblock %}